name: face-recon
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy>=1.20.0
  - opencv>=4.5.0
  - flask>=2.0.0
  - dlib>=19.24
  - cmake
  - pip
  - pip:
      - face_recognition>=1.3.0
      - imutils>=0.5.0
      - isort[colors]>=5.10.0
