name: CI/CD Security System

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3
        
      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer avhengigheter
        run: pip install -r requirements.txt

      - name: Kjør tester
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend til server
        run: ssh user@server "cd /security-system && git pull && systemctl restart security-system"
