name: CI/CD Security System

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v3
        
      - name: Sett opp Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer avhengigheter
        run: pip install -r requirements.txt

      - name: Kjør tester
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend til server
        run: |
          ssh user@server << 'EOF'
          set -e
          echo "[INFO] Starting deployment to security system server"
          
          echo "[INFO] Changing to security-system directory"
          cd /security-system || { echo "[ERROR] Failed to change to /security-system directory"; exit 1; }
          
          echo "[INFO] Pulling latest changes from git repository"
          git pull || { echo "[ERROR] Failed to pull latest changes from git"; exit 1; }
          
          echo "[INFO] Restarting security-system service"
          systemctl restart security-system || { echo "[ERROR] Failed to restart security-system service"; exit 1; }
          
          echo "[SUCCESS] Deployment completed successfully"
          EOF
